name: Create Staging Release PR

on:
  push:
    branches:
    - master

jobs:
  staging-release-pr:
    name: Create Staging Release PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: Wuerike/standard-version-release-branch@1.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          origin_branch: master
          target_branch: staging
          as_draft: true
          pr_template: 'PR opened by [standard-version-release-branch](https://github.com/Wuerike/standard-version-release-branch)'
