name: Create Staging Release PR

on:
  push:
    branches:
    - master

jobs:
  staging-release-pr:
    name: Create Staging Release PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Changelog
        id: generate_changelog
        uses: nblagoev/pull-release-notes-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          base-ref: master
          head-ref: release
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "staging"
          pr_title: "IGNORE: auto pr test"
          # pr_body: |
          #   ## Changes:
          #   <!-- START pr-commits -->
          #   <!-- END pr-commits -->
          pr_body: ${{steps.generate_changelog.outputs.result}}
          pr_draft: true
