# Creates or updates a PR from master to staging
# where body is auto filled with pull requests merged as history
# that triggers whenever a push/merge is done on master.

name: Create Staging Pull Request

on:
  push:
    branches:
    - master

jobs:
  staging-pull-request:
    name: Create Staging Pull Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Creates pull request as draft, ignores if already created
      - name: Create pull request
        run: gh pr create -B staging -H master -t 'Staging Release' -b '' -d
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Update pull request body
        uses: k3rnels-actions/pr-update@v2.0.0  # Currently cannot create draft PR
        id: pr_update
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_title: Staging Release
          pr_source: master
          pr_target: staging
          pr_body: |
            ### Changes
          pr_body_with_links: true
